// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqizbwmrjbymusrfrcly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxaXpid21yamJ5bXVzcmZyY2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDUyMTUsImV4cCI6MjA2MjI4MTIxNX0.f7ACrkJVX88JDXfC-UWmO_P9W0ySbMr71KOIAP8gvrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);